services:

  postgres:
    image: postgres:16-alpine
    container_name: smartbancs-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartbancs-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

  bancs-mock:
    build:
      context: ./bancs-mock
    container_name: smartbancs-bancs-mock
    environment:
      MOCK_ERROR: ${MOCK_ERROR:-}
    ports:
      - "8001:8000"

  worker:
    build:
      context: ./worker
    container_name: smartbancs-worker
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      BANCS_MOCK_URL: http://bancs-mock:8000
      POLL_INTERVAL_SECONDS: 5
      HTTP_TIMEOUT_SECONDS: 5
    depends_on:
      - postgres
      - bancs-mock

  ai-worker:
    build:
      context: ./ai-worker
    container_name: smartbancs-ai-worker
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: